---
# Application info
info:
  app:
    name: ABNAMRO Coding Challenge
    description: ABNAMRO Coding Challenge.
    javaVersion: ${java.version}
    operatingSystem: ${os.name} ${os.version} (${os.arch})

# General Spring configuration
spring:
  main:
    banner-mode: "off"
  jackson:
    default-property-inclusion: NON_EMPTY
    deserialization:
      fail-on-unknown-properties: false   
    serialization:
      write-dates-as-timestamps: false   
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

# The base path for the Spring Actuator APIs
management:
  endpoint.health.show-details: "always"
  endpoints.enabled-by-default: true
  endpoints.web.exposure.include: "*"
  endpoints.jmx.exposure.include: "*"

# Configuration for Logback.
logging:
  config: classpath:logback-spring.xml
  path : classpath:logs





data:
 filefields: 
      client_information:
        startIndex: '3'
        endIndex: '18'
        sumRequired: false
        actionRequired: 'ADD'
      product_information:
        startIndex: '25'
        endIndex: '45'
        sumRequired: false
        actionRequired: 'ADD'
      quantity_long:
        startIndex: '52'
        endIndex: '62'
        sumRequired: true
        actionRequired: 'ADD'
      quantity_short:
        startIndex: '62'
        endIndex: '72'
        sumRequired: true
        actionRequired: 'SUB'

      
 rowlength: '303'
 csvFields : CLIENT_INFORMATION,PRODUCT_INFORMATION,TOTAL_TRANSACTION_AMOUNT
 outputFileName : Output.csv
  
 
